# Generated by Django 4.1.5 on 2023-02-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfem_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
    ]
